version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - pern
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - pern
    environment:
      # Replace with your Neon database credentials
      - DATABASE_URL=postgresql://neondb_owner:npg_A69xHWlJLNvR@ep-restless-paper-addt9m0o-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - PORT=5000

networks:
  pern:
    driver: bridge
